### ISSUE TITLE
composer circular dependency

### ISSUE THREAD

**Issue by ontoplocal** [windwalker-io/query#2]
windwalker/query requires itself as dependency
![2018-12-05_15h33_36](https://user-images.githubusercontent.com/12156899/49548595-76208300-f8a3-11e8-9bf9-906be0b1198a.png)

**Comment by asika32764** [comment]
It because windwalker/renderer 3.4.9 has a wrong release yesterday, please remove `windwalker/renderer` folder and re-run composer update, it should be fixed now.
